spring.application.name=${APP_NAME}

# Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Update the Schema (Create tables automatically)
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}

# Show SQL (Optional - helps you see what's happening)
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect